/* Generated By:JavaCC: Do not edit this line. IDLParserConstants.java */
package parsing.javaccparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 34;
  /** RegularExpression Id. */
  int OCTALINT = 35;
  /** RegularExpression Id. */
  int DECIMALINT = 36;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 37;
  /** RegularExpression Id. */
  int FLOATONE = 38;
  /** RegularExpression Id. */
  int FLOATTWO = 39;
  /** RegularExpression Id. */
  int CHARACTER = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int ANOTATION = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"package\"",
    "\";\"",
    "\"//@\"",
    "\"=\"",
    "\".\"",
    "\"class\"",
    "\"enum\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"extends\"",
    "\"const\"",
    "\"[\"",
    "\"]\"",
    "\"virtual\"",
    "\"float\"",
    "\"double\"",
    "\"int\"",
    "\"short\"",
    "\"long\"",
    "\"byte\"",
    "\"boolean\"",
    "\"string\"",
    "\"<\"",
    "\">\"",
    "\"true\"",
    "\"false\"",
    "<ID>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "<ANOTATION>",
  };

}
