package TestAll;

/* ========================================
   The BaseData() is used as a test for ...
=========================================== */

//
//kalle

class BaseData
{
    /* hej hopp */
    string baseText;
    string[] stringOpenArr;
    string[5] stringFixArr;

    string<23> fixLengthString;
    string<16>[] fixLengthStringOpenArr;
    string<16>[10] fixLengthStringFixArr;
}
