package TestAll;

//Dummy data extending BaseData and adding fields of all available types
//including aggregating a third data type TestData
class ChildData extends BaseData
{
    /* */
    boolean bo;
    /* */
    byte b;
    /* */
    short sh;
    /* */
    int i;
    /* */
    long l;
    /* */
    float f;
    /* */
    double d;

    /* This string shall hold the word World */
    string s;

    /* */
    TestData test2;
    /* */
    virtual TestAll.TestData testPointer;

    /* */
    Fruit fruit;

    /* */
    boolean[] bos;
    boolean[11] fbos;
    /* */
    byte[] bs;
    byte[256] fbs;
    /* */
    short[] shs;
    short[4] fshs;
    /* */
    int[] is_;
    int[3] fis_;
    /* */
    long[] ls;
    long[6] fls;
    /* */
    float[] fs;
    float[77] ffs;
    /* */
    double[] ds;
    double[5] fds;
    /* */
    string[] ss;
    string[10] fss;
    /* */
    virtual TestData[] test2s;
    virtual TestData[5] ftest2s;
    /* */
    virtual TestData[] secondVirtArray;
    virtual TestData[7] fsecondVirtArray;
    /* */
    TestData[] test2s2;
    TestData[4] ftest2s2;
    /* */
    Fruit[] fruitarr;
    Fruit[15] ffruitarr;
    
}
